#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 2
bspc config window_gap 15

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false


bspc rule -r "*"
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Alacritty state=floating
bspc rule -a Lollypop desktop='^4'
bspc rule -a discord desktop='^5'


setxkbmap gb
wmname compiz

picom &
flameshot &
nm-applet &

walset &

killall -wq polybar; polybar bspwmbar

