#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


if [ "$(uname -n)" = "tobypc" ]; then
    bspc monitor DP-1 -d 1 2 3 4 5
    bspc monitor DP-2 -d 6 7 8 9 0
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -r "*"
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom &
flameshot &
nm-applet &

sh ~/Scripts/Environment/polybar.sh
sh ~/Scripts/Environment/wallpaper.sh
